export const LoaderConfig = {
    obstacle1 : require("../sprites/obstacle1.png"),
    obstacle2 : require("../sprites/obstacle2.png"),
    obstacle3 : require("../sprites/obstacle3.png"),
    obstacle4 : require("../sprites/obstacle4.png"),
    road : require("../sprites/road.png"),
    // player : require("../sprites/player.png"),
    player2 : require("../sprites/player2.png"),

    union : require("../sprites/union.png"),
    obstacle5: require("../sprites/obstacle5.png"),
    // finalbg: require("../sprites/finalbg.png"),
    // hurray: require("../sprites/Hurray_UI.png"),
    // mainmenu: require("../sprites/mainmenu.png"),
    // finalbg2: require("../sprites/finalbg2.png"),
    // finalbg3: require("../sprites/finalbg3.png"),
    finalbg4 : require("../sprites/hurray.png"),
    // mainmenu2: require("../sprites/mainmenu2.png"),
    // mainmenu3: require("../sprites/mainmenu3.png"),
    // button: require("../sprites/Enabled.png"),
    mainmenu4: require("../sprites/mainmenu4.png"),
    shadow: require("../sprites/shadow.png"),
    button1: require("../sprites/Button1.png"),
}